### ISSUE TITLE
Invalid dataset name silent error

### ISSUE THREAD

**Issue by Zolmeister** [indeedeng/iupload#1]
Invalid dataset names (not matching `[a-z0-9]+` are displayed in the uploader, but the files are never indexed. This fails silently. The UI should alert the user that their dataset is named incorrectly (as well as validate names created from the tool)

(Edit: Also the name restriction feels arbitrary, and should probably allow '_')

**Comment by jx-opher** [comment]
I ran into this issue as well. The documentation says "If the process fails, failed shows as the status.", but when the root cause is an invalid name there is no indication the indexing process has stopped.
* The UI should prevent users from creating datasets with invalid names
* Errors that prevent an index from being created should update the UI with a "failed" status.
